name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Use Node 20.x
      uses: actions/setup-node@v4.0.1
      with:
        node-version: 20.x
        cache: npm
    - run: npm ci
    - run: npm test
